### ISSUE TITLE
Conflict between BugTorch and WitchingGadgets

### ISSUE THREAD

**Issue by Khikki** [jss2a98aj/BugTorch#3] opened 2021-02-16 17:59 UTC
Hi, I noticed a conflict between BugTorch and Witching Gadgets, can you advise how to fix it?
[latest.log](https://github.com/jss2a98aj/BugTorch/files/5990614/latest.log) or https://pastebin.com/LfiqYajS

https://www.curseforge.com/minecraft/mc-mods/witching-gadgets

**Comment by jss2a98aj** [comment] 2021-02-18 21:23
Disabling the mixin in the bugtorch config that touches the block class should be fine for the moment. I have a better way to achieve the same end result that will be used in the next major update.

**Comment by Khikki** [comment] 2021-12-28 17:21
Hello-Hello! I noticed that you have become more active in updating the BugTorch, but the problem has not been resolved, there is also an error, but of a different kind. https://pastebin.com/nFvGAMuU

**Comment by jss2a98aj** [comment] 2021-12-28 20:51
`Caused by: java.lang.NoClassDefFoundError: ru/timeconqueror/spongemixins/MinecraftURLClassPath`
I think you need to update SpongeMixins. That class was added to it in version 1.3.0.

**Comment by Khikki** [comment] 2022-01-01 15:35
Happy New Year, I apologize for not answering earlier, that's how I updated SpongeMixins 1.4.0, but the issue is still present. https://pastebin.com/51x0FuCt

**Comment by Khikki** [comment] 2022-01-01 16:14
more problems with other mods: https://pastebin.com/ZPFaKYVK

**Comment by makamys** [comment] 2022-01-01 16:24
I managed to reproduce your original issue, and adding [Mixingasm](https://github.com/makamys/Mixingasm) seems to have fixed it. It may fix the new one as well, can you try it?

**Comment by Roadhog360** [comment] 2022-03-09 17:11
@Khikki Is this still an issue even after the above mod is added?

**Comment by jss2a98aj** [comment] 2023-01-29 03:13
As Mixingasm appears to be the solution and there have been no further replies, I am now closing this issue.

**Closed by jss2a98aj** 2023-01-29 03:13 UTC
